const ATTESTATION_NULLIFIER_DOMAIN = BigInt(1)

const EPOCH_KEY_NULLIFIER_DOMAIN = BigInt(2)

const KARMA_NULLIFIER_DOMAIN = BigInt(3)

export {
    ATTESTATION_NULLIFIER_DOMAIN,
    EPOCH_KEY_NULLIFIER_DOMAIN,
    KARMA_NULLIFIER_DOMAIN,
}