const DEFAULT_START_KARMA = 20

const DEFAULT_STATE_TRANSITION_KARMA = 20

const DEFAULT_POST_KARMA = 10

const DEFAULT_COMMENT_KARMA = 5

const MAX_KARMA_BUDGET = 10

const DEFAULT_AIRDROPPED_KARMA = 20

export {
    DEFAULT_START_KARMA,
    DEFAULT_STATE_TRANSITION_KARMA,
    DEFAULT_POST_KARMA,
    DEFAULT_COMMENT_KARMA,
    MAX_KARMA_BUDGET,
    DEFAULT_AIRDROPPED_KARMA,
}